language: ruby
sudo: false

cache: bundler

rvm:
  - 2.3.1
  - 2.2.5

env:
  - DB=postgres
  - DB=mysql
  - DB=sqlite3

before_script:
  - mysql -e 'create database simple_taggable;'
  - psql -c 'create database simple_taggable;' -U postgres
  - bundle exec rake test:copy_migrations

gemfile:
  - gemfiles/rails_4.1.gemfile
  - gemfiles/rails_4.2.gemfile
  - gemfiles/rails_5.0.gemfile
  - gemfiles/rails_edge.gemfile

matrix:
  allow_failures:
    - gemfile: gemfiles/rails_edge.gemfile
  exclude:
    - rvm: 2.1
      gemfile: gemfiles/rails_edge.gemfile

notifications:
  email:
    on_success: change
